---
- name: is CloudWatch Agent already installed?
  apt:
    name: amazon-cloudwatch-agent
    state: present
  ignore_errors: yes
  register: already_inst

- block:
  - block:
    - name: purge existing pkg if installed
      apt:
        name: amazon-cloudwatch-agent
        state: absent
        purge: yes
    when: (already_inst is success)
  - name: make temp dir for installation files
    file:
      path: "/tmp/aws-cwa-inst"
      state: "directory"
  - name: download & unpack the latest cloudwatch agent .zip
    unarchive:
      remote_src: "yes"
      src: "https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip"
      dest: "/tmp/aws-cwa-inst/"
  - name: run the installer
    shell: cd /tmp/aws-cwa-inst && echo 'N' | ./install.sh
    notify: restart-amazon-cloudwatch-agent
  - name: remove temp dir
    file:
      path: "/tmp/aws-cwa-inst/"
      state: "absent"
  when: (already_inst is failed) or (aws_install_latest)
  ignore_errors: "{{ ansible_check_mode }}"

- name: place cloudwatch agent config(s)
  template:
    src: "{{ item }}"
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/{{ item | basename | regex_replace('\\.j2','') }}"
    mode: 0644
  with_fileglob:
  - "{{ aws_cwa_cfgs }}/*.json.j2"
  notify: restart-amazon-cloudwatch-agent

- name: ensure log groups exist
  shell: |
    aws --profile AmazonCloudWatchAgent logs create-log-group --log-group-name {{item.log_group_name}}{% if item.log_group_tags is defined and item.log_group_tags|length > 0 %} --tags {% for lgti in item.log_group_tags %}{% for tK in lgti %}{{tK}}={{ lgti[ tK ] }}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}{% endif %}{{ "" }}
  args:
    executable: '/bin/bash'
  register: create_log_groups
  loop: "{{ aws_cwa_logfiles | default([]) }}"
  run_once: true
  failed_when: create_log_groups.rc != 0 and create_log_groups.rc != 255

- name: ensure retention policies are up to date
  shell: |
    {% if item.log_retention|default('') != '' %}
    aws --profile AmazonCloudWatchAgent logs put-retention-policy --log-group-name {{item.log_group_name}} --retention-in-days {{item.log_retention}}
    {% else %}
    aws --profile AmazonCloudWatchAgent logs delete-retention-policy --log-group-name {{item.log_group_name}}
    {% endif %}
  args:
    executable: '/bin/bash'
  register: create_log_groups
  with_items: "{{ aws_cwa_logfiles | default([]) }}"
  run_once: true
  failed_when: create_log_groups.rc != 0 and create_log_groups.rc != 255

- name: enable service on boot
  service:
    name: "amazon-cloudwatch-agent"
    enabled: "yes"

- name: Add log rotation for amazon-cloudwatch-agent.log
  copy:
    dest: '/etc/logrotate.d/aws-cloudwatch-agent'
    owner: 'root'
    group: 'root'
    content: |
        /opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log {
            size 50M
            rotate 5
            compress
            missingok
            copytruncate
        }
