---
aws_cwa_namespace: 'YourNamespace'
aws_cwa_cfgs: 'group_files/awscwa_cfg/generic'
aws_cwa_disk_monitor_paths:
  - "/"
  - "/var"
aws_cwa_logfiles:
  - file_path: '/var/log/syslog'
    log_group_name: 'system-logs'
    log_group_tags:
      - TagKey: TagValue
      - AnotherTag: AnotherValue
    log_stream_name: '{{ansible_hostname}}/syslog'
    log_retention: '14'
    timestamp_format: '%b %-d %H:%M:%S'
    timezone: "LOCAL"